apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 5m
  resources:
    - ./clusters/minikube/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

