apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: observability  # Change if needed
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: "25.7.0"  # Check latest version
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: true
    server:
      service:
        type: ClusterIP

